Django-polls/poll/accounts/urls.py
from django.urls import path

from . import views

app_name ='accounts'

urlpatterns = [
 #accounts
    path('person/',views.person,name='person'),
    path('',views.index, name="Index"),
    path('details/<int:id>/',views.detail,name='details'),
    path('edit/<int:id>/', views.edit_event, name="edit_event"),
    path('eventform/', views.event, name="eventform"),
    path('login/', views.logg, name='log'),
    path('logout/', views.logo, name='logout'),
    path('register/',views.register,name='register'),
]

Django-polls/poll/poll/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('testapp.urls',namespace='testapp')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('change-password/', auth_views.PasswordChangeView.as_view()),

]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Django-polls/poll/testapp/urls.py
from django.urls import path

from . import views
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

app_name='testapp'

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('class/', views.MyView.as_view(), name='cool'),
    path('about/', login_required(TemplateView.as_view(template_name="testapp/detail.html")))
]

Django-polls/poll/testapp/models.py
from django.db import models

# Create your models here.
from django.db import models
import datetime
from django.utils import timezone

class Question(models.Model):
    Question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data published')

    def __str__(self):
        return str(self.Question_text)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Cho(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        #s=""
        return self.choice_text



from django.db import models

class Publication(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ('title',)

class Article(models.Model):
    headline = models.CharField(max_length=100)


    def __str__(self):
        return self.headline

    class Meta:
        ordering = ('headline',)


class link(models.Model):
    publication = models.ForeignKey(Publication, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)


Django-polls/poll/testapp/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.shortcuts import get_object_or_404, render
from .models import Question,Cho
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'testapp/index.html', context)




def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'testapp/detail.html', {'question': question})





@login_required
def vote(request,question_id):
    print(request.POST)

    print(dir(request),request.user)
    question = get_object_or_404(Question, pk=question_id)
    print(question.pub_date)
    if request.POST.get('choice'):
        selected_choice = question.cho_set.get(pk=request.POST.get('choice'))
        print(request.user.is_authenticated)
        #poll = question
        selected_choice.votes += 1
        selected_choice.save()
    else:
        messages.error(request, 'NO choice!')
        return HttpResponseRedirect(reverse('testapp:detail', args=(question.id,)))

    return render(request, 'testapp/results.html', {'poll': question})




from django.http import HttpResponse
from django.views import View



class MyView(View):
    def get(self, request):
        # <view logic>
        print(dir(self))
        print(MyView.as_view.__doc__)
        return HttpResponse('result')

Django-polls/poll/templates/testapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>


   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    </head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
  <a class="navbar-brand" href="#">Logo</a>

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">


        {% if request.user.is_authenticated %}
        <a class="nav-link" href="">{{request.user.username}}</a>
{% else %}

      <a class="nav-link" href="{% url 'accounts:log' %}">Login</a>
{% endif %}




    </li>
    <li class="nav-item">


{% if request.user.is_authenticated %}
        <a class="nav-link" href="{% url 'accounts:logout' %}">logout</a>
{% else %}

      <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
{% endif %}
    </li>

  </ul>
</nav>

<div class="container-fluid">

</div>
<br>
<br>
{% block content %}


{% endblock %}
</body>
</html>

















Django-polls/poll/templates/testapp/detail.html
{% extends 'testapp/base.html' %}



{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }} </li>
    {% endfor %}
</ul>
{% endif %}

<h1>{{ question.Question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'testapp:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.cho_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

{% endblock %}

Django-polls/poll/templates/testapp/index.html
{% extends 'testapp/base.html' %}



{% block content %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'testapp:detail' question.id %}" >{{ question.Question_text }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p> No polls are available.</p>
{% endif %}

{% endblock %}


Django-polls/poll/templates/testapp/results.html
{% extends 'testapp/base.html' %}


{% block content %}
{% if error %}
    <h1> Error!</h1>

{% else %}

   {% for x in poll.cho_set.all %}
           <ul>

               <li>   {{x}}  ---  {{x.votes}} </li>

           </ul>
   {% endfor %}
{% endif %}
{% endblock %}
