dofast/urls.py
from django.contrib import admin
from django.urls import path,include
from profilepic import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from chat.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('register.urls')),
    path('profile/', user_views.profile, name='profile'),
    path('chat/',index,name='chat'),

]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

poll/poll/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('testapp.urls',namespace='testapp')),
    path('accounts/', include('accounts.urls', namespace='accounts'))

]

register/urls.py
from django.urls import path
from .views import *
app_name ='accounts'

urlpatterns = [
    path('',index1.as_view(),name='Index1'),
    path('edit_profile/',edit_profile,name="edit_profile"),
    path('change_password/', change_password , name="change_password"),
    path('login/', Login.as_view(), name='Login'),
    path('logout/', Logout.as_view(), name='Logout'),
    path('register/',Register,name='Register'),
    path('Thanks/',Thanks.as_view(),name='Thanks'),
    path('change-password/', password_change, name='passwordchange'),
    path('eventform/', event, name="eventform"),
    path('edit/<int:id>/',edit_event, name="edit_event"),
    path('details/<int:id>/', detail, name='details'),
    path('index', index, name="Index"),
    path('event_register/',event_register,name='event_register'),
]

urls.py
from django.urls import path

from . import views

app_name='accounts'

urlpatterns = [
    # ex: /polls
    path('login/', views.logg, name='log'),
    path('logout', views.logo, name='logout'),
    path('register',views.register,name='register'),
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    #path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    #path('<int:question_id>/vote/', views.vote, name='vote'),
]

theme/dofast/register/models.py
from django.db import models

# Create your models here.


from django.contrib.auth.models import User
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    is_individual = models.BooleanField(default=False)
    is_corporate = models.BooleanField(default=False)


class Individual(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_name = models.CharField(max_length=40)
    pass_word = models.CharField(max_length=20)
    status = models.BooleanField()
    img=models.ImageField(null=True)
    def __str__(self):

        return self.user_name


class Corporate(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_name=models.CharField(max_length=20)
    pass_word=models.CharField(max_length=25)
    cname=models.CharField(max_length=40)
    service=models.CharField(max_length=40)


    def __str__(self):
        return self.user_name

register/forms.py
from .models import Individual,User,event_creation
from django.forms import ModelForm

class IndividualForm(ModelForm):
    class Meta:
        model=Individual
        fields =('user_name','email','first_name','last_name','phone_no','state','district','city_or_town','pass_word')


from .models import Corporate

from django.forms import ModelForm

class CorporateForm(ModelForm):
    class Meta:
        model = Corporate
        fields =('company_name','CIN','sub_category','ROC','branch','email',
                 'pass_word')


from django.contrib.auth.forms import UserChangeForm


class editprofileform(UserChangeForm):
    class Meta:
        model = User
        fields =('username',
                  'email',
                 'password',
                 )

class eventform(ModelForm):
    class Meta:
        model = event_creation
        exclude =('user',)



class editform(ModelForm):
    class Meta:
        model =event_creation
        exclude = ('numv',)


from .models import event_contrib


class EventRegister(ModelForm):
    class Meta:
        model = event_contrib
        exclude =('membercount',)



class Eventcool(ModelForm):
    class Meta:
        model = event_contrib
        fields ='__all__'

theme/dofast/register/forms.py
from .models import Individual,User
from django.forms import ModelForm



class IndividualForm(ModelForm):
    class Meta:
        model=Individual
        exclude=('user',)
# Create your models here.



from .models import Corporate

from django.forms import ModelForm

class CorporateForm(ModelForm):
    class Meta:
        model = Corporate
        exclude=('user',)


from django.contrib.auth.forms import UserChangeForm


class editprofileform(UserChangeForm):
    class Meta:
        model = User
        fields =('username',
                  'email',
                 'password',

                 )

register/views.py
from django.shortcuts import render
from django.contrib import messages
from .forms import IndividualForm, CorporateForm, editprofileform
from django.shortcuts import redirect
from django.views.generic import View
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout
from .models import Individual, Corporate, vote
from .models import User
from django.contrib.auth import update_session_auth_hash
# from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib.auth.hashers import make_password
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .forms import IndividualForm, CorporateForm, event_creation, editform, eventform,EventRegister,Eventcool
from django.db.models import Count

def event_register(request):
    if request.method == "POST":
        if request.user.is_corporate:
            form= Eventcool(request.POST)
            if(form.is_valid()):
                form.save()
        else:
            form =EventRegister(request.POST)
            if(form.is_valid()):
                form.save()
        return redirect('accounts:Index')

    if request.user.is_corporate:
        form = Eventcool()
    else:
        form = EventRegister()

    return render(request,'register/event_register.html',{'form':form})




def index(requests):
    event_o = event_creation.objects.filter(user__username=requests.user)
    eventobj = event_creation.objects.exclude(user__username__contains=requests.user)

    if(requests.method=='GET'):
        if 'title' in requests.GET:
            event_o=event_o.order_by('event_name')
            eventobj = eventobj.order_by('event_name')

        if 'pub_date' in requests.GET:
            pass
            #event_o = event_o.order_by('event_name')
            #eventobj = eventobj.order_by('event_name')
        if 'num_votes' in requests.GET:
            event_o =event_o.annotate(Count('vote')).order_by('-vote__count')

        if 'search' in requests.GET:
            search=requests.GET['search']
            event_o=event_o.filter(event_name__icontains=search)




    paginator = Paginator(event_o, 5)
    page = requests.GET.get(' page')
    event_o = paginator.get_page(page)

    if requests.method == 'POST':
        print(requests.path)
        id = requests.POST['id']
        o = event_creation.objects.get(id=id)
        if not o.user_can_vote(requests.user):
            messages.error(requests, 'Already voted!')
            return render(requests, 'register/index1.html', {'myself': event_o, 'others': eventobj})
        new_vote = vote(user=requests.user, event=o)
        new_vote.save()
        o.numv = o.numv + 1
        o.save()

    else:
        pass


    return render(requests, 'register/index1.html', {'myself': event_o, 'others': eventobj})


@login_required
def detail(request, id):
    obj = get_object_or_404(event_creation, id=id)
    return render(request, 'register/detail.html', {'obj': obj})


@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
    else:
        form = PasswordChangeForm(request.user)
        return render(request, 'register/password_changeform.html', {'form': form})


@login_required
def edit_event(request, id):
    print(id)
    obj = get_object_or_404(event_creation, id=id)
    print(obj)
    if request.user != obj.user:
        return redirect('/')

    if request.method == 'POST':
        form = editform(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            messages.success(request, 'Details updated!!', extra_tags='alert alert-success alert-dismissible fade show')
            return redirect('accounts:Index')

    else:
        form = editform(instance=obj)
    return render(request, 'register/edit_event_form.html', {'form': form})


@login_required
def event(request):
    print(request.user.username)
    form = eventform()
    if request.method == 'POST' and request.user.is_authenticated:
        print(request.POST)

        u = eventform(request.POST)
        # __mail(request.POST['event_name'])
        if u.is_valid():
            o = request.user
            c = u.save(commit=False)
            c.user = o
            c.save()
        messages.success(request, 'Details updated!!', extra_tags='alert alert-success alert-dismissible fade show')
        return redirect('accounts:Index')
    return render(request, 'register/event_form.html', {'form': form})


@login_required
def edit_profile(request):
    if request.method == "POST":
        form = editprofileform(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return render(request, 'register/index1.html', {})
    else:
        form = editprofileform(instance=request.user)
        args = {'form': form}
        return render(request, 'register/edit_profile.html', args)


@login_required
def change_password(request):
    if request.method == "POST":
        print(request.POST)
        form = PasswordChangeForm(user=request.user, data=request.POST)
        print(form.is_valid())
        if form.is_valid():
            form.save()
            print("cool")
            print(request.user)
            update_session_auth_hash(request, form.user)
            return render(request, 'register/index1.html', {})
            # render(request,'register/edit_profile.html',{})
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'register/change_password.html', args)


class Thanks(TemplateView):
    template_name = "register/thanks.html"


class index1(TemplateView):
    template_name = 'register/index1.html'


def Register(request):
    context = {}
    l = len(request.POST)
    print(l)
    u = 0
    if request.method == 'POST' and 'gender' not in request.POST:
        if l == 10:
            print(request.POST)
            print(request.FILES)
            u = IndividualForm(request.POST, request.FILES)
            print(u.is_valid())
            print(u.errors)
            context['errors'] = u.errors
            if u.is_valid():
                username = u.cleaned_data['user_name']
                pass_word = u.cleaned_data['pass_word']
                enc_password = make_password(pass_word)
                user = User(username=username, password=enc_password)
                user.is_individual = True
                user.is_corporate = False
                user.save()
                print(user)
                use = User.objects.get(username=username)
                c = u.save(commit=False)
                c.user = use
                c.save()
                messages.success(request, 'Thanks for registring {}'.format(username))
                return redirect('accounts:Login')
        else:
            print('*********COOL***********')
            print(request.POST)
            u = CorporateForm(request.POST)
            if u.is_valid():
                username = u.cleaned_data['company_name']
                pass_word = u.cleaned_data['pass_word']
                enc_password = make_password(pass_word)
                user = User(username=username, password=enc_password)
                user.is_individual = False
                user.is_corporate = True
                user.save()
                print(user)
                use = User.objects.get(username=username)
                c = u.save(commit=False)
                c.user = use
                c.save()
                messages.success(request, 'Thanks for registring {}'.format(username))
                return redirect('accounts:Login')

    else:
        print(request.POST)
        context['gender'] = 1
        print(request.POST.get('gender'), type(request.POST.get('gender')))
        if (request.POST.get('gender') == 'male'):
            context['gender'] = 1
        elif request.POST.get('gender') == 'female':
            context['gender'] = 0

        print('hello', context['gender'])

        if context.get('gender') == 1:
            form = IndividualForm()
            context['form'] = form
        elif context.get('gender') == 0:
            form = CorporateForm()
            context['form'] = form
        print(context)

    if 'errors' in context:
        context['form'] = IndividualForm
        context['gender'] = 1
        print(context)
    return render(request, 'register/register_form.html', context)


class Login(View):
    def post(self, requests, *args, **kwargs):
        print(requests.user)
        print(requests.method)
        print(requests.POST)
        l = len(requests.POST)
        if requests.method == 'POST' and 'gender' not in requests.POST:
            if l == 3:
                username = requests.POST.get('username')
                password = requests.POST.get('password')
                print(username)
                print(password)
                user = authenticate(requests, username=username, password=password)
                print(user)

                if user is not None:
                    print("sdkjakj")
                    u = User.objects.get(username=username)

                    # if u.is_individual == True and u.is_corporate == False:
                    print("cool!")
                    login(requests, user)
                    return redirect('accounts:Index')
                else:
                    print("fasjk")
                    messages.error(requests, 'Bad request')
                    return redirect('accounts:Login')
            else:
                print("else ...man! ")

templates/register/change_password.html
{% extends 'Base.html' %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}

    {{form.as_p}}
<input type="submit">
</form>


{% endblock %}

templates/register/detail.html
{% extends 'Base.html' %}

{% block content %}


{{obj}}
<form method="POST" action="{% url 'accounts:Index' %}">
{% csrf_token %}
<input type = "hidden" name = "id" value = "
{{obj.id}}" />
<button type="submit" class="btn btn-info">Vote</button>


</form>
{% endblock %}

templates/register/edit_event_form.html
{% extends 'Base.html' %}


{% block content %}


<div class="container">


    <form action=" " method ="POST">
        {% csrf_token %}
    {{form.as_p}}

    <input type="submit">
           </form>
</div>



{% endblock %}

templates/register/edit_profile.html
{% extends 'Base.html' %}

{% block content %}

<form action="" method="post">
{% csrf_token %}
    {{form.as_p}}
<input type="submit">
</form>


{% endblock %}

templates/register/event_form.html
{% extends 'Base.html' %}
{% block content %}


<div class="container">
    <form action=" " method ="POST">
        {% csrf_token %}
    {{form.as_p}}

    <input type="submit">
           </form>
</div>


{% endblock %}

templates/register/event_register.html
{% extends 'Base.html' %}


{% block content %}


<div class="container">
    <form action="{% url 'accounts:event_register' %}" method ="POST">
        {% csrf_token %}

        {{form.as_p}}
         <input type="submit">

           </form>
</div>


{% endblock %}


templates/register/index.html
{% extends 'Base.html' %}

{% block content %}

<div class="jumbotron">

    <div class="row">

     <div class="col">
      <a href="{% url 'accounts:eventform' %}">
      <button type="button" class="btn btn-primary">
          Create Event
      </button>

  </a>

     <br>
     <br>

{% if messages %}

    {% for message in messages %}
<div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
     {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
    {% endfor %}

{% endif %}
         <ul class="list-group">
 {% for i in myself %}
             <li class="list-group-item" >
     <a href="{% url 'accounts:details' %}" >
         {{i.id}}
       {{i.user}}
       {{i.event_name}}
    {{i.event_location}}
         </a>
     {{i.num_votes}}
 {% if request.user == i.user %}
 <a  class="float-right" href= "{% url 'accounts:edit_event' i.id  %}" >   <i class="far fa-edit"></i>   </a>
                 {% endif %}
             </li>
  {% endfor %}
             </ul>
<br><br>
               <div class="pagination">
    <span class="step-links">
        {% if myself.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ myself.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ myself.number }} of {{ myself.paginator.num_pages }}.
        </span>

        {% if myself.has_next %}
            <a href="?page={{ myself.next_page_number }}">next</a>
            <a href="?page={{ myself.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>





         <ul class="list-group">
 {% for i in others %}
             <li class="list-group-item" >
     <a href="" >
       {{i.user}}
       {{i.event_name}}
    {{i.event_location}}
         </a>
<a href="" class = "float-right" ><button type="button" class="btn btn-primary">Register</button></a>

             </li>
  {% endfor %}
             </ul>

<br>

</div>
    </div>
</div>

{% endblock %}

templates/register/index1.html
{% extends 'Base.html' %}


{% block title %}
<title> Index1</title>
{% endblock %}

{% block content %}


<div class="jumbotron">

    <div class="row">

        <div class="col">
            <a href="{% url 'accounts:eventform' %}">
                <button type="button" class="btn btn-primary">
                    Create Event
                </button>
            </a>

            <br>
            <br>

            {% if messages %}

            {% for message in messages %}
            <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endfor %}

            {% endif %}

            <form class="form-inline my-2 my-lg-1">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>

            <a href="?title=True"
               class="btn btn-{% if 'title' in request.GET %}warning{% else %}primary{% endif%}"
               style="margin-bottom:5px">A-Z</a>


            <a href="?pub_date="
               class="btn btn-{% if 'pub_date' in request.GET %}warning{% else %}primary{% endif%}"
               style="margin-bottom:5px">pub_date</a>

            <a href="?num_votes=True"
               class="btn btn-{% if 'num_votes' in request.GET %}warning{% else %}primary{% endif%}"
               style="margin-bottom:5px">Votes</a>


            <ul class="list-group">
                {% for i in myself %}
                <li class="list-group-item">
                    <a href="{% url 'accounts:details' i.id %}">
                        {{i.id}}
                        {{i.user}}
                        {{i.event_name}}
                        {{i.event_location}}
                    </a>

                    {{i.num_votes}}
                    {% if request.user == i.user %}
                    <a class="float-right" href="{% url 'accounts:edit_event' i.id  %}"><i class="far fa-edit"></i></a>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
            <br><br>


            <div class="pagination">
                <span class="step-links">
        {% if myself.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ myself.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
                   Page {{ myself.number }} of {{ myself.paginator.num_pages }}.
        </span>

        {% if myself.has_next %}
            <a href="?page={{ myself.next_page_number }}">next</a>
            <a href="?page={{ myself.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
            </div>


            <ul class="list-group">
                {% for i in others %}
                <li class="list-group-item">
                    <a href="">
                        {{i.id}}
                        {{i.user}}
                        {{i.event_name}}
                        {{i.event_location}}
                    </a>
                    <a href="{% url 'accounts:event_register'  %}" class="float-right">
                        <button type="button" class="btn btn-primary">Register</button>
                    </a>

                </li>
                {% endfor %}
            </ul>
            <br>

        </div>
    </div>
</div>


{% endblock %}

templates/register/index_chat.html
{% extends "Base.html" %}
{% load staticfiles %}
{% block title %}<title>Mul Chat</title> {% endblock %}
<!--{% block header_text %}MultiChat Example{% endblock %}-->

{% block extra_head %}

<link rel="stylesheet" href="{% static " css/style.css" %}" type="text/css" media="screen" />
<script src="{% static " js/jquery-1.12.2.min.js" %}" type="text/javascript"></script>
	<script src="{% static "js/reconnecting-websocket.min.js" %}" type="text/javascript"></script>

{% endblock %}


{% block content %}

<ul class="rooms">
    {% for room in rooms %}
    <li class="room-link" data-room-id="{{ room.id }}">{{ room }}</li>
    {% empty %}
    <p class="empty">No chat rooms defined. Maybe make some in the <a href="{% url 'admin:index' %}">admin</a>?</p>
    {% endfor %}
</ul>

<div id="chats">
</div>

{% endblock %}

{% block extra_body %}
<script>
        $(function () {
            // Correctly decide between ws:// and wss://
            var ws_scheme = window.location.protocol == "https:" ? "wss" : "ws";
            var ws_path = ws_scheme + '://' + window.location.host + "/chat/stream/";
            console.log("Connecting to " + ws_path);


            //------------------------
            var socket = new ReconnectingWebSocket(ws_path);
            //------------------------
            // Handle incoming messages



            socket.onmessage = function (message) {
                // Decode the JSON
                console.log("Got websocket message " + message.data);


                var data = JSON.parse(message.data);
                // Handle errors
                if (data.error) {
                    alert(data.error);
                    return;
                }
                // Handle joining
                if (data.join) {
                    console.log("Joining room " + data.join);
                    var roomdiv = $(
                            "<div class='room' id='room-" + data.join + "'>" +
                            "<h2>" + data.title + "</h2>" +
                            "<div class='messages'></div>" +
                            "<form><input><button>Send</button></form>" +
                            "</div>"
                    );
                    // Hook up send button to send a message
                    roomdiv.find("form").on("submit", function () {
                        socket.send(JSON.stringify({
                            "command": "send",
                            "room": data.join,
                            "message": roomdiv.find("input").val()
                        }));
                        roomdiv.find("input").val("");
                        return false;
                    });
                    $("#chats").append(roomdiv);
                    // Handle leaving
                } else if (data.leave) {
                    console.log("Leaving room " + data.leave);
                    $("#room-" + data.leave).remove();
                    // Handle getting a message
                } else if (data.message || data.msg_type != 0) {
                    var msgdiv = $("#room-" + data.room + " .messages");
                    var ok_msg = "";
                    // msg types are defined in chat/settings.py
                    // Only for demo purposes is hardcoded, in production scenarios, consider call a service.
                    switch (data.msg_type) {
                        case 0:
                            // Message
                            ok_msg = "<div class='message'>" +
                                    "<span class='username'>" + data.username + "</span>" +
                                    "<span class='body'>" + data.message + "</span>" +
                                    "</div>";
                            break;
                        case 1:
                            // Warning / Advice messages
                            ok_msg = "<div class='contextual-message text-warning'>" + data.message +
                                    "</div>";
                            break;
                        case 2:
                            // Alert / Danger messages
                            ok_msg = "<div class='contextual-message text-danger'>" + data.message +
                                    "</div>";
                            break;
                        case 3:
                            // "Muted" messages
                            ok_msg = "<div class='contextual-message text-muted'>" + data.message +
                                    "</div>";
                            break;
                        case 4:
                            // User joined room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " joined the room!" +
                                    "</div>";
                            break;
                        case 5:
                            // User left room
                            ok_msg = "<div class='contextual-message text-muted'>" + data.username +
                                    " left the room!" +
                                    "</div>";
                            break;
                        default:
                            console.log("Unsupported message type!");
                            return;
                    }
                    msgdiv.append(ok_msg);

                    msgdiv.scrollTop(msgdiv.prop("scrollHeight"));
                } else {
                    console.log("Cannot handle message!");
                }
            };

            // Says if we joined a room or not by if there's a div for it
            inRoom = function (roomId) {
                return $("#room-" + roomId).length > 0;
            };

            // Room join/leave
            $("li.room-link").click(function () {
                roomId = $(this).attr("data-room-id");
                if (inRoom(roomId)) {
                    // Leave room
                    $(this).removeClass("joined");
                    socket.send(JSON.stringify({
                        "command": "leave",
                        "room": roomId
                    }));
                } else {
                    // Join room
                    $(this).addClass("joined");
                    socket.send(JSON.stringify({
                        "command": "join",
                        "room": roomId
                    }));
                }
            });

            // Helpful debugging
            socket.onopen = function () {
                console.log("Connected to chat socket");
            };


            socket.onclose = function () {
                console.log("Disconnected from chat socket");
            }
        });



</script>
{% endblock %}

templates/register/password_changeform.html
{% extends 'accounts/base.html' %}


{% block content %}

<form action=" {% url 'accounts:passwordchange' " method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" >
</form>


{% endblock %}

templates/register/register_form.html
{% extends 'Base.html' %}


{% block content %}

<h2>Select the category</h2>

<form action="{% url 'accounts:Register'%}" method="post" enctype="multipart/form-data">
{% csrf_token %}


    {% if gender == 1  %}
    <input type="radio" id="cool" name="gender"  checked  value="male" onclick="this.form.submit()"> Individual
        <input type="radio"  name="gender" value="female" onclick="this.form.submit()"> Corporate

    {%elif gender == 0 %}
            <input type="radio" id="cool" name="gender"   value="male" onclick="this.form.submit()"> Individual

    <input type="radio"  name="gender"  checked value="female" onclick="this.form.submit()"> Corporate

    {% endif %}

</form>


{% if form %}
<form action=" {% url 'accounts:Register' %} " method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    {% if gender == 0 %}
    <b>NetWort(>5 Cr.):</b><input type="radio" name="worth" value="Yes" checked> Yes
            <input type="radio" name="worth" value="No"> No<br>
    {% endif %}
    <input type="submit" >
</form>

{% endif %}

<p> {{errors}} </p>



{% endblock content %}
































<!--
<h2>Select the category</h2>

<form action="{% url 'accounts:Register'%}" method="post">
{% csrf_token %}
    {% if gender == 1  %}
    <input type="radio" id="cool" name="gender"  checked  value="male" onclick="this.form.submit()"> Male
        <input type="radio"  name="gender" value="female" onclick="this.form.submit()"> Female

    {%elif gender == 0 %}
            <input type="radio" id="cool" name="gender"   value="male" onclick="this.form.submit()"> Male

    <input type="radio"  name="gender"  checked value="female" onclick="this.form.submit()"> Female

    {% else %}
       <input type="radio" id="cool" name="gender"  value="male" onclick="this.form.submit()"> Male
        <input type="radio"  name="gender" value="female" onclick="this.form.submit()"> Female

    {% endif %}
</form>


<script>



</script>




<p id="demo"></p>









{% if form %}
<form action=" {% url 'accounts:Register' %} " method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" >
</form>

{% endif %}


<p> {{gender}}</p>

-->