theme/dofast/dofast/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('register.urls'))
]

theme/dofast/register/urls.py
from django.urls import path
from .views import *
app_name ='accounts'

urlpatterns = [
    path('',index.as_view(),name='Index'),
    path('edit_profile/',edit_profile,name="edit_profile"),
    path('change_password/', change_password , name="change_password"),

    path('login/', Login.as_view(), name='Login'),
    path('logout/', Logout.as_view(), name='Logout'),

    path('register/',Register.as_view(),name='Register'),
    path('Thanks/',Thanks.as_view(),name='Thanks'),
]

theme/dofast/templates/Base.html
<!DOCTYPE html>
<html lang="en">
  <head>

      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

  {% block title %}
  <title>
    Base
  </title>
  {% endblock %}

  </head>

  <body>


<nav classLoader="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      {% if user.is_authenticated %}
                    <li class="active"><a href="">{{user.username}}</a></li>
      {% else %}
                      <li class="active"><a href="{% url 'accounts:Register' %}">Register</a></li>


      {% endif %}
      {% if user.is_authenticated %}
      <li><a href="{% url 'accounts:Logout'  %}">Logout</a></li>
   {%else %}
            <li><a href="{% url 'accounts:Login'  %}">Login</a></li>
   {% endif %}

        </ul>
  </div>
</nav>


<div class="container">
  <div class="jumbotron">
  </div>

</div>

    {% block content %}


     {% endblock %}





<!-- /.container -->






  </body>
</html>